export const IS_DEV = process.env.EXPO_PUBLIC_ENVIRONMENT === "development";
export const EXPO_PUBLIC_APP_VERSION = process.env.EXPO_PUBLIC_APP_VERSION;
export const EXPO_PUBLIC_RUNTIME_VERSION =
  process.env.EXPO_PUBLIC_RUNTIME_VERSION;
export const EXPO_PUBLIC_BUILD_VERSION = process.env.EXPO_PUBLIC_BUILD_VERSION;
export const EXPO_PUBLIC_ENVIRONMENT = process.env.EXPO_PUBLIC_ENVIRONMENT;
export const EXPO_PUBLIC_APP_NAME = process.env.EXPO_PUBLIC_APP_NAME;
export const EXPO_PUBLIC_APP_IDENTIFIER =
  process.env.EXPO_PUBLIC_APP_IDENTIFIER;
