export const SCREENS = {
  HOME_TABS: "HomeTabs",
  HOME: "Home",
  NOTIFICATIONS: "Notifications",
  ONBOARDING: "Onboarding",
  POSTING: "Posting",
  PROFILE_HOME: "ProfileHome",
  SPLASH: "Splash",
  SIGN_UP: "SignUp",
  NOSTR_UP: "NostrUp",
  LOGIN: "Login",
  NOSTR_IN: "NostrIn",
  INTERESTS: "Interests",
  COMPLETE_PROFILE: "CompleteProfile",
  RECOVERY_EMAIL: "RecoveryEmail",
  RESET_PASSWORD: "ResetPassword",
} as const;
